version: "3.7"

services:
  api:
    environment:
      ROOT_DOMAIN: "http://localhost"
      API_DOMAIN: "http://localhost:3000"
      DASH_DOMAIN: "http://localhost:4200"
      NODE_ENV: "dev"
    ports:
      - "127.0.0.1:3000:3000"

  dash:
    build:
      args:
        - DASH_ENV=dev
    volumes:
      - ./services/dash/src:/usr/dash/services/dash/src
      - ./services/dash/.next:/usr/dash/services/dash/.next
      - ./services/dash/public:/usr/dash/services/dash/public
    ports:
      - "127.0.0.1:4200:4200"

  proxy-healthcheck:
    environment:
      NODE_ENV: "dev"

  job-runner:
    environment:
      NODE_ENV: "dev"
    volumes:
      - ../screenshots:/usr/job-runner/screenshots

  grafana:
    environment:
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    expose:
      - "5000"
    ports:
      - "127.0.0.1:5000:5000"
