version: "3.7"

services:
  nginx:
    build:
      args:
        - NGINX_ENV=prod
  dash:
    build:
      args:
        - DASH_ENV=prod

  # api:
  #   expose:
  #     - "3000"
  #   environment:
  #     DOMAIN: https://api.gaiusbot.me
  #     DASH_DOMAIN: https://dash.gaiusbot.me

  grafana:
    environment:
      GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: "false"
      GF_SERVER_DOMAIN: "stats.soulkiller.io"
      GF_SERVER_ROOT_URL: "stats.soulkiller.io"
