version: "3.7"

services:
  postgres:
    build:
      context: ./docker/postgresql
      dockerfile: ./Dockerfile
    environment:
      POSTGRES_USER: "soulkiller"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "soulkiller"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    ports: 
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U soulkiller"]
      interval: 10s
      timeout: 5s

  postgres-exporter:
    image: wrouesnel/postgres_exporter:latest
    environment:
      DATA_SOURCE_NAME: "postgres://soulkiller:admin@postgres:5432/soulkiller?sslmode=disable"
    restart: unless-stopped

  redis:
    image: redis:5-alpine
    volumes:
      - redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      timeout: 5s

  redis-exporter:
    image: oliver006/redis_exporter:alpine
    environment:
      REDIS_ADDR: "redis://redis:6379"
    restart: unless-stopped

  api:
    build:
      context: ./
      dockerfile: ./docker/api/Dockerfile
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    environment: 
      DISCORD_SCOPES: "identify,email"
      DB_URL: "postgres://soulkiller:admin@postgres:5432/soulkiller"
      STRIPE_PRICE_ID: "price_1IflayLoZxvFDzrnkopX8bUP"

  dash:
    build:
      context: ./
      dockerfile: ./docker/dash/Dockerfile
    depends_on:
      - api
    restart: unless-stopped

  prometheus:
    build:
      context: ./docker/prometheus
      dockerfile: Dockerfile
    volumes:
      - prometheus-data:/prometheus
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', "wget -qO- localhost:9000/-/healthy"]
      interval: 30s
      timeout: 5s

  grafana:
    build:
      context: ./docker/grafana
      dockerfile: Dockerfile
    environment:
      GF_SERVER_HTTP_PORT: "5000"
      GF_DEFAULT_INSTANCE_NAME: "soulkiller"
      GF_ANALYTICS_REPORTING_ENABLED: "false"
      GF_DATABASE_TYPE: "postgres"
      GF_DATABASE_URL: "postgres://soulkiller:admin@postgres:5432/soulkiller?sslmode=disable"
      GF_AUTH_GITHUB_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "false"
      GF_AUTH_GITHUB_ALLOW_SIGN_UP: "true"
      GF_AUTH_GITHUB_CLIENT_ID: "a4e42bd86651c4d929e8"
      GF_AUTH_GITHUB_SCOPES: "user:email,read:org"
      GF_AUTH_AUTH_URL: "https://github.com/login/oauth/authorize"
      GF_AUTH_TOKEN_URL: "https://github.com/login/oauth/access_token"
      GF_AUTH_API_URL: "https://api.github.com/user"
      GF_AUTH_ALLOWED_ORGANIZATIONS: "soulkiller.io"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

volumes:
  postgres-data:
    name: "soulkiller-postgres-data"
  redis-data:
    name: "soulkiller-redis-data"
  prometheus-data:
    name: "soulkiller-prometheus-data"
  grafana-data:
    name: "soulkiller-grafana-data"
