version: "3.7"

services:
  nginx:
    build:
      args:
        - NGINX_ENV=prod
  dash:
    build:
      args:
        - DASH_ENV=prod

  api:
    environment:
      ROOT_DOMAIN: "https://soulkiller.io"
      API_DOMAIN: "https://api.soulkiller.io"
      NODE_ENV: "prod"

  grafana:
    environment:
      GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: "false"
      GF_SERVER_DOMAIN: "stats.soulkiller.io"
      GF_SERVER_ROOT_URL: "stats.soulkiller.io"
